services:
  web:
    image: d3vle0/asmr:latest
    environment:
      # ICECAST_BASE_URL: ${ICECAST_BASE_URL}
      ICECAST_BASE_URL: https://radio.katusa.xyz
    ports:
      - "4173:80"
    restart: unless-stopped
